POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "visitante@email.com",
    "password": "123456"
}

###
GET http://localhost:3003/contract/0177e3bc-9e63-4154-8ff0-4106d3813a88
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiZGQ3ZTdmM2ItYTZmZi00ZWQ1LWIzZmMtNWEzOWQ0M2RjZjY1IiwiaWF0IjoxNjg4ODU4NzI5LCJleHAiOjE2ODg4NjIzMjl9.SWkn81JmH3w3CpvCP7OzUmBOFPUj1ODBxy-oCaJLaZk